source "https://rubygems.org"

ruby "3.4.9"

gem "rails", "~> 7.1.2"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "honeybadger"
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "inline_svg"
gem "jbuilder"
gem "measured-rails"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"

gem "sprockets-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "pry-rails"
  gem "web-console"
end

group :development do
  gem "standard"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
